"""add booking cancellation fields

Revision ID: 259f21e95190
Revises: b15f0431cf91
Create Date: 2026-09-25 23:55:21.606297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259f21e95190'
down_revision: Union[str, Sequence[str], None] = 'b15f0431cf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'cancellation_reason')
    # ### end Alembic commands ###
