"""add package pricing and promotions

Revision ID: 2c0fa5651b31
Revises: 428b783e5f74
Create Date: 2026-09-27 22:43:08.149995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0fa5651b31'
down_revision: Union[str, Sequence[str], None] = '428b783e5f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_day_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_package_day_prices_day_of_week'),
    sa.CheckConstraint('price >= 0', name='ck_package_day_prices_price'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'day_of_week', name='uq_package_day_prices_package_day')
    )
    op.create_index(op.f('ix_package_day_prices_package_id'), 'package_day_prices', ['package_id'], unique=False)
    op.create_table('package_promotions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('promotional_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_on >= starts_on', name='ck_package_promotions_dates'),
    sa.CheckConstraint('promotional_price >= 0', name='ck_package_promotions_price'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_promotions_package_id'), 'package_promotions', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_promotions_package_id'), table_name='package_promotions')
    op.drop_table('package_promotions')
    op.drop_index(op.f('ix_package_day_prices_package_id'), table_name='package_day_prices')
    op.drop_table('package_day_prices')
    # ### end Alembic commands ###
